# Generated by Django 4.0.2 on 2022-03-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ware_house_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=20)),
                ('serial_number', models.CharField(max_length=20)),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('storage_space', models.FloatField()),
                ('weight', models.IntegerField()),
                ('storage_name', models.CharField(max_length=20)),
                ('locate', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
