# Generated by Django 4.0.2 on 2022-03-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_ware_house_model_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware_house_model',
            name='height',
            field=models.FloatField(null=True),
        ),
    ]
