# Generated by Django 4.0.2 on 2022-03-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_ware_house_model_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware_house_model',
            name='customer_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ware_house_model',
            name='customer_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ware_house_model',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ware_house_model',
            name='description',
            field=models.CharField(default='', max_length=30),
        ),
    ]
